/******************************************************************************
 * This file is part of the cvc5 project.
 *
 * Copyright (c) 2009-2026 by the authors listed in the file AUTHORS
 * in the top-level source directory and their institutional affiliations.
 * All rights reserved.  See the file COPYING in the top-level source
 * directory for licensing information.
 * ****************************************************************************
 *
 * Ideal-membership strategies for finite-field polynomials.
 */

#ifdef CVC5_USE_COCOA

#include "cvc5_private.h"

#ifndef CVC5__THEORY__FF__IDEAL_MEMBERSHIP_H
#define CVC5__THEORY__FF__IDEAL_MEMBERSHIP_H

// external includes
#include <CoCoA/BigIntOps.H>
#include <CoCoA/ideal.H>

// std includes
#include <memory>
#include <optional>
#include <vector>

// internal includes
#include "theory/ff/cocoa_util.h"
#include "util/resource_manager.h"

namespace cvc5::internal {
namespace theory {
namespace ff {

/** Interface for sound ideal-membership tests and polynomial reduction. */
class IdealMembership
{
 public:
  virtual ~IdealMembership() = default;
  /** Return true only if this strategy establishes that the ideal contains p.
   */
  virtual bool contains(const Poly& p) const = 0;
  /** Return a polynomial congruent to p modulo this strategy's generators. */
  virtual Poly reduce(const Poly& p) const = 0;
};

/** CoCoA ideal membership without eagerly requesting its Groebner basis. */
class CocoaIdealMembership : public IdealMembership
{
 public:
  CocoaIdealMembership();
  explicit CocoaIdealMembership(const Polys& generators);
  bool contains(const Poly& p) const override;
  Poly reduce(const Poly& p) const override;

 protected:
  /** CoCoA's representation of the ideal. Empty if the ideal is 0. */
  std::optional<CoCoA::ideal> d_ideal;
};

/** Eager CoCoA Groebner-basis specialization of ideal membership. */
class Gb : public CocoaIdealMembership
{
 public:
  Gb();
  /** A GB for the ideal generated by generators */
  Gb(const Polys& generators, const ResourceManager* rm);
  /** Is this GB's ideal equal to the whole ring? */
  bool isWholeRing() const;
  /** Is this GB's ideal zero-dimensional? */
  bool zeroDimensional() const;
  /** Compute a minimal q such that q(p) = 0 mod this GB's ideal. */
  Poly minimalPolynomial(const Poly& p) const;
  /** List the elements of the GB */
  const Polys& basis() const;

 private:
  /** The GB. Empty if the ideal is 0. */
  Polys d_basis;
};

/** Ideal membership accelerated by independent power-difference rules. */
class PowerDifferenceIdealMembership : public IdealMembership
{
 public:
  /** Strategy for generic generators in an ideal with power rules. */
  enum class MixedIdealStrategy
  {
    /** Use only the reduced generic ideal; sound but possibly incomplete. */
    RELAXED,
    /** Compute the complete ideal for exact mixed membership. */
    COMPLETE_GB,
  };

  /**
   * Build membership for generators. By default, mixed ideals use only their
   * reduced generic generators after power reduction. COMPLETE_GB opts into an
   * eager basis of the complete ideal when exact mixed membership is required.
   */
  PowerDifferenceIdealMembership(
      const Polys& generators,
      const ResourceManager* rm,
      MixedIdealStrategy strategy = MixedIdealStrategy::RELAXED);
  bool contains(const Poly& p) const override;
  Poly reduce(const Poly& p) const override;
  /** Whether the ideal contains arithmetic power-difference rules. */
  bool hasPowerDifferenceRules() const { return !d_powerRules.empty(); }

 private:
  /**
   * A normalized rule x^high = scale*x^low for one variable.
   * For example, generator x^5 + 2*x^2 gives
   * {index(x), 5, 2, -2, x^5 + 2*x^2}.
   */
  struct PowerRule
  {
    size_t d_variable;
    CoCoA::BigInt d_high;
    CoCoA::BigInt d_low;
    Scalar d_scale;
    Poly d_generator;

    /** Apply x^high = scale*x^low to one monomial. */
    void apply(CoCoA::BigInt& exponent, Scalar& coefficient) const
    {
      if (exponent < d_high)
      {
        return;
      }

      // Reduce e to low + (e - low) mod (high - low). For low=0, this
      // specializes to ordinary quotient-and-remainder power reduction.
      const CoCoA::BigInt step = d_high - d_low;
      const CoCoA::BigInt remainder = d_low + (exponent - d_low) % step;
      const CoCoA::BigInt applications = (exponent - remainder) / step;
      coefficient *= CoCoA::power(d_scale, applications);
      exponent = remainder;
    }
  };
  /** Extract independent univariate binomials; return all other generators. */
  Polys extractPowerRules(const Polys& generators);
  /** Apply every independent rule to one monomial. */
  void applyPowerRules(std::vector<CoCoA::BigInt>& exponents,
                       Scalar& coefficient) const;
  /**
   * Reduce using only the extracted rules. Do not implement this through
   * CoCoA ideal operations such as NF or IsElem: those may construct and cache
   * a full Groebner basis, adding terms redundant for power-rule reduction.
   */
  Poly reducePowerRules(const Poly& p) const;
  /** Independent arithmetic rules that form a basis for the power subideal. */
  std::vector<PowerRule> d_powerRules;
  /** Membership strategy applied after custom power-rule reduction. */
  std::unique_ptr<IdealMembership> d_remainderMembership;
};

}  // namespace ff
}  // namespace theory
}  // namespace cvc5::internal

#endif /* CVC5__THEORY__FF__IDEAL_MEMBERSHIP_H */

#endif /* CVC5_USE_COCOA */
